### ISSUE TITLE
Update section "Testing Locally" based on new TaskCat version 0.9.x

### ISSUE THREAD

**Issue by edselg** [aws-quickstart/quickstart-workshop#20]
The current version of TaskCat is 0.9.8.
This version has a new cli interface that is not compatible with version 0.8.27 used in the steps in the current version of the workshop.

The following error is seen when running through the steps in [70_testing/1_local_test.html](https://github.com/aws-quickstart/quickstart-workshop/blob/develop/content/70_testing/1_local_test.md):

**Issue**
> version 0.9.8
> usage: taskcat [args] <command> [args] [subcommand] [args] 
> taskcat: error: argument : invalid choice: 'qs-workshop/ci/taskcat.yml' (choose from 'delete', 'deploy', 'lint', 'list', 'package', 'test')

**Steps to Reproduce**
The issue can be seen following the steps in "Running tests" with the virtual environment:
```
cd ~/environment
taskcat -c qs-workshop/ci/taskcat.yml &> screen-logs.txt &
```

**Fix**
The fix for the issue is to use the syntax of TaskCat and redirect stdout and stderr:
```
cd ~/environment
taskcat test run -p qs-workshop > screen-logs.txt 2>&1 &
```

Changes to 1_local_test.html in relation to TaskCat:
1. Update gif file taskcat-install.gif to show new version of taskcat
2. In BONUS Section, refer to new format of TaskCat configuration <PROJECT_ROOT>/.taskcat.yml to override parameters instead of using ~/.aws/taskcat_global_override.json.

When running with a ~/.aws/taskcat_global_override.json the following message is shown:

> version 0.9.8
> [WARN   ] : failed to load config from /home/ec2-user/environment/qs-workshop/.taskcat.yml
> [WARN   ] : config is in a legacy format, support for which will be dropped in a future version. a new format config (.taskcat.yml) will been placed in your project_root
> [WARN   ] : overrides file /home/ec2-user/.aws/taskcat_global_override.json is in legacy format, support for this format will be deprecated in a future version.
> [WARN   ] : Converting overrides to new format and saving in /home/ec2-user/.taskcat.yml

**Note:** There could also be a mention of <PROJECT_ROOT>.taskcat_overrides.yml.

3. Update to the taskcat command line as shown above.

**Resources:**
* https://github.com/aws-quickstart/taskcat#migrating-from-08x

**Note:** Running TaskCat with the current version of the workshop results on a number of Lint errors and warnings, These issues will be reported separately since the changes need to happen in the https://github.com/aws-quickstart/quickstart-workshop-labs repo.

**Comment by sshvans** [comment]
Instructions and artifacts updated to taskcat v9 in #21
